# Generated by Django 4.0.1 on 2022-01-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addstock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('productcode', models.CharField(max_length=20)),
                ('productprice', models.IntegerField()),
                ('actualprice', models.IntegerField()),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addstock.addstockmodel')),
            ],
        ),
    ]
