# Generated by Django 4.0.1 on 2022-01-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductmodel',
            name='brandname',
            field=models.CharField(max_length=20),
        ),
    ]
