# Generated by Django 4.0 on 2022-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=20)),
                ('hsncode', models.IntegerField(default=0)),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField(default=0)),
                ('actualprice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stockadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=20)),
                ('productname', models.CharField(max_length=50)),
                ('availbags', models.IntegerField(default=0)),
                ('availpieces', models.IntegerField(default=0)),
            ],
        ),
    ]
