# Generated by Django 4.0 on 2022-01-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=20)),
                ('hsncode', models.IntegerField(default=0)),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField(default=0)),
                ('actualprice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stockadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availbags', models.IntegerField(default=0)),
                ('availpieces', models.IntegerField(default=0)),
                ('brandname', models.ForeignKey(db_column='agencyuser_brandname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sto_brandname', to='agencyuser.productadd')),
                ('productname', models.ForeignKey(db_column='agencyuser_productname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sto_productname', to='agencyuser.productadd')),
            ],
        ),
    ]
